---
- name: Play for repository
  connection: local
  gather_facts: false
  hosts: localhost
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: Creating repository
      ansible.builtin.file:
        mode: '0755'
        path: "{{ repository_directory }}"
        state: directory
      tags: create

    - name: Uninstalling repository
      ansible.builtin.shell: >
        find
        {{ repository_directory }}
        -mindepth
        1
        -delete
      changed_when: true
      tags: uninstall

    - name: Installing repository
      ansible.builtin.git:
        dest: "{{ repository_directory }}"
        repo: "{{ repository_url }}"
      tags: install

    - name: Deleting repository
      ansible.builtin.file:
        path: "{{ repository_directory }}"
        state: absent
      tags: delete
