---
- name: Play for repository
  connection: local
  gather_facts: false
  hosts: localhost
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: Creating venv
      ansible.builtin.file:
        mode: '0755'
        path: "{{ repository_directory }}"
        state: directory
      tags: create
